### ISSUE TITLE
corde dump on unparseable XML-files

### ISSUE THREAD

**Issue by ScuttleSE** [comictagger/comictagger#126]
`[scuttle@ranma comictagger]$ ./comictagger.py 
Traceback (most recent call last):
  File "/home/scuttle/comictagger/comictaggerlib/taggerwindow.py", line 1031, in selectFile
    self.fileSelectionList.addPathList(fileList)
  File "/home/scuttle/comictagger/comictaggerlib/fileselectionlist.py", line 212, in addPathList
    row = self.addPathItem(f)
  File "/home/scuttle/comictagger/comictaggerlib/fileselectionlist.py", line 339, in addPathItem
    self.updateRow(row)
  File "/home/scuttle/comictagger/comictaggerlib/fileselectionlist.py", line 393, in updateRow
    fi.ca.readCIX()
  File "/home/scuttle/comictagger/comicapi/comicarchive.py", line 998, in readCIX
    self.cix_md = ComicInfoXml().metadataFromString(raw_cix)
  File "/home/scuttle/comictagger/comicapi/comicinfoxml.py", line 49, in metadataFromString
    tree = ET.ElementTree(ET.fromstring(string))
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 380
Aborted (core dumped)
`

This happends when you open a folder or a list of files and one of them has invalid XML-data. Kinda annoying since the errormessage doesn't tell you which file is the culprit...

**Comment by lordwelch** [comment]
@ScuttleSE if this happens again feel free to re-open
