### ISSUE TITLE
[Bug] Failed installation of PyQt5 on Termux

### ISSUE THREAD

**Issue by lasersPew** [comictagger/comictagger#191]
Here is the output by `pip install comictagger`
`Collecting comictagger
  Using cached comictagger-1.3.0a0.tar.gz (627 kB)
Collecting configparser
  Using cached configparser-5.0.2-py3-none-any.whl (19 kB)
Requirement already satisfied: beautifulsoup4>=4.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from comictagger) (4.9.3)
Collecting natsort==3.5.2
  Using cached natsort-3.5.2-py2.py3-none-any.whl (25 kB)
Collecting PyPDF2==1.24
  Using cached PyPDF2-1.24.tar.gz (59 kB)
Collecting pillow>=4.3.0
  Using cached Pillow-8.3.1.tar.gz (48.7 MB)
Collecting PyQt5>=5.12.2
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done                                      Getting requirements to build wheel ... done                                  Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpv51i9ft1
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_189dc2bfcd0648e4bd332913701697ce
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lmmkztac/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpv51i9ft1 Check the logs for full command output.
  Using cached PyQt5-5.15.3.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmp4m2r_htn
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_65e64bec62f848d5a6f254d9a0f41743
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-1ekkjzrc/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6e/86/d715e71771cece0e060f2ebab20f3ded067b08a0927dfb3143530cae8098/PyQt5-5.15.3.tar.gz#sha256=965ba50e7029b37f218a54ace24e87c77db3e5a9f0b83baeb21fb57b4154b838 (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmp4m2r_htn Check the logs for full command output.
  Using cached PyQt5-5.15.2.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpm2yzh5wj
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_2904fa29f67a4a6c88a2cec8f8084377
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-n05chqbf/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz#sha256=372b08dc9321d1201e4690182697c5e7ffb2e0770e6b4a45519025134b12e4fc (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpm2yzh5wj Check the logs for full command output.
  Using cached PyQt5-5.15.1.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpr3pac4x1
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_823733d95b1a4e2b8d62a3bc7016c826
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 64, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-3f_8q87t/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1d/31/896dc3dfb6c81c70164019a6cbba6ab037e3af7653d9ca60ccc874ee4c27/PyQt5-5.15.1.tar.gz#sha256=d9a76b850246d08da9863189ecb98f6c2aa9b4d97a3e85e29330a264aed0f9a1 (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpr3pac4x1 Check the logs for full command output.
  Using cached PyQt5-5.15.0.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpfpjy5w6w
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_b3487b353441402ca9f1154693ddfea5
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rx_4zynr/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz#sha256=c6f75488ffd5365a65893bc64ea82a6957db126fbfe33654bcd43ae1c30c52f9 (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpfpjy5w6w Check the logs for full command output.
  Using cached PyQt5-5.14.2.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpd99jobw5
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-9lfxwl25/pyqt5_24dde63ad66541d4a993a79e36760456
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-kr3czukz/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz#sha256=bd230c6fd699eabf1ceb51e13a8b79b74c00a80272c622427b80141a22269eb0 (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.5). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpd99jobw5 Check the logs for full command output. ...`

I don't mind just using the CLI.

**Comment by lordwelch** [comment]
@lasersPew with the latest alpha release it is now possible to install ComicTagger on termux.
I just tested with a clean install of termux.
you need to run these commands
```bash
pkg upgrade
pkg upgrade
pkg install clang libjpeg-turbo python
LDFLAGS="-L/system/lib64/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow
pip install comictagger
```
