### ISSUE TITLE
Advertisment vs Advertisement

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#232]
The schema: https://github.com/anansi-project/comicinfo/blob/main/schema/v2.0/ComicInfo.xsd
Has the page type as: "Advertisment" (no e)
Our code has: "Advertisement" (with e)

I noticed the issue when loading an archive with the schema's value (no e), and the application crashes on save (as below).

It is a simple change and I can create a pull request - but then all old archives with the old spelling could similarly crash.

A cleaner approach might be to default the old value to the new one silently, but it would require an archive save to fix permanently in the archive's xml file.

Thoughts?

Traceback (most recent call last):
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 2063, in fileListSelectionChanged
    self.loadArchive(fi.ca)
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 2081, in loadArchive
    self.actualLoadCurrentArchive()
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 610, in actualLoadCurrentArchive
    self.pageListEditor.setData(self.comic_archive, self.metadata.pages)
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/pagelisteditor.py", line 275, in setData
    item = QListWidgetItem(self.listEntryText(p))
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/pagelisteditor.py", line 287, in listEntryText
    text += " (" + self.pageTypeNames[page_dict['Type']] + ")"
KeyError: 'Advertisment'
Traceback (most recent call last):
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 2063, in fileListSelectionChanged
    self.loadArchive(fi.ca)
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 2067, in loadArchive
    self.clearForm()
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/taggerwindow.py", line 748, in clearForm
    self.pageListEditor.setData(self.comic_archive, self.metadata.pages)
  File "/home/michael.fitzurka/Projects/comictagger/comictaggerlib/pagelisteditor.py", line 271, in setData
    self.listWidget.itemSelectionChanged.disconnect(self.changePage)
TypeError: 'method' object is not connected
Aborted (core dumped)

**Comment by lordwelch** [comment]
Well this is definitely a problem that we crash on invalid data. But I believe it's actually a bug in the schema.
The schemas for this format have never been 100% accurate. You can check to see what [ComicRack](https://web.archive.org/web/20180926062727/http://comicrack.cyolito.com/downloads) puts out, as it invented the format.

**Comment by MichaelFitzurka** [comment]
Downloaded the app and you are correct, the value from ComicRack is Advertisement with an "e".
I submitted a pull request to change their specs: https://github.com/anansi-project/comicinfo/pull/20.
I'll make a fix here to stop the crash on an invalid value, but not change the Advertisement value itself.

**Comment by lordwelch** [comment]
Awesome! Thanks for the work you're putting in

**Comment by lordwelch** [comment]
Merged
