### ISSUE TITLE
comictagger crashing on start-up (Arch Linux)

### ISSUE THREAD

**Issue by brolyxxx** [comictagger/comictagger#267]
- OS: Arch Linux 5.17.1-arch1-1 x86_64

Hi, I installed the package using this [PKGBUILD](https://aur.archlinux.org/packages/comictagger) in the AUR, this is the output of `pacman -Qi comictagger`:

- Name            : comictagger
- Version         : 1.3.2.alpha.4-1
- Description     : Application for writing metadata to digital comics, written in Python and PyQt
- URL             : https://github.com/comictagger/comictagger
- Depends On      : python  python-beautifulsoup4  python-natsort  python-pillow  python-requests  python-pycountry  python-py7zr  python-unrar-cffi python-pyqt5  python-pybcj
- Optional Deps   : None

```
python 3.10.4-1
python-beautifulsoup4 4.10.0-1
python-natsort 8.1.0-1
python-pillow 9.1.0-1
python-requests 2.27.1-1
python-pycountry 22.3.5-1
python-py7zr 0.18.3-1
python-unrar-cffi 0.2.2-2
python-pyqt5 5.15.6-7
python-pybcj 0.5.2-1
python-brotli 1.0.9-7
```

In addition to the dependencies listed in the PKGBUILD I installed python-brotli because of this error:
`pkg_resources.DistributionNotFound: The 'brotli>=1.0.9; platform_python_implementation == "CPython"' distribution was not found and is required by py7zr`

Now I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/comictagger", line 33, in <module>
    sys.exit(load_entry_point('comictagger==0.0.0', 'console_scripts', 'comictagger')())
  File "/usr/bin/comictagger", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/comictaggerlib/main.py", line 28, in <module>
    from comictaggerlib import cli
  File "/usr/lib/python3.10/site-packages/comictaggerlib/cli.py", line 29, in <module>
    from comictaggerlib.comicvinetalker import ComicVineTalker, ComicVineTalkerException
  File "/usr/lib/python3.10/site-packages/comictaggerlib/comicvinetalker.py", line 31, in <module>
    from comictaggerlib import ctversion
ImportError: cannot import name 'ctversion' from 'comictaggerlib' (/usr/lib/python3.10/site-packages/comictaggerlib/__init__.py)
```

It used to work some time ago so I suspect it has something to do with Python 3.10. Is there any chance to run comictagger with Python 3.10?

Thanks

**Comment by lordwelch** [comment]
I'm not sure why it worked before but the packager for Arch linux needs to either install the dependencies listed in requirements_dev.txt before building or use the source distribution from [pypi](https://pypi.org/project/comictagger/)

The issue regarding the python-brotli library will need to be taken up with the packager of the py7zr library

**Comment by brolyxxx** [comment]
Thanks @lordwelch, I added more makedepends to the PKGBUILD as you suggested but the error persists. I'll report the issue to the AUR packager and see if someone else has the same issue on Arch

**Comment by brolyxxx** [comment]
Ok, the PKGBUILD has been updated by the maintainer and now everything works as expected, I'm closing this issue.
