### ISSUE TITLE
Immediate crash when opening comicbook

### ISSUE THREAD

**Issue by ScuttleSE** [comictagger/comictagger#308]
Doesn't matter if I select only one, multiple, or a folder, when I open comicbooks with comictagger it seems to scan through them, then it crashes with this message:

```
2022-06-05T18:17:04 | comictagger | CRITICAL | Uncaught exception: TypeError: setValue(self, float): argument 1 has unexpected type 'NoneType'
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 2035, in file_list_selection_changed
    self.load_archive(fi.ca)
  File "/home/scuttle/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 2053, in load_archive
    self.actual_load_current_archive()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 596, in actual_load_current_archive
    self.metadata_to_form()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 790, in metadata_to_form
    self.dsbCommunityRating.setValue(md.community_rating)
TypeError: setValue(self, float): argument 1 has unexpected type 'NoneType'
```

**Comment by ScuttleSE** [comment]
Installed from source

**Comment by lordwelch** [comment]
Thanks for the issue, should be fixed in the latest commit
