### ISSUE TITLE
Corrupt zipfiles crashes program

### ISSUE THREAD

**Issue by ScuttleSE** [comictagger/comictagger#309]
When doing Auto Tag on a large batch of files, the program crashes when it encounters a corrupt zipfile.

Opening the file in comictagger works fine, it's when you try to save that comictagger crashes. 

```
2022-06-06T12:27:10 | comicapi.comicarchive | ERROR | Error reading zip archive [[Errno 22] Invalid argument]: /media/Collections/Comics/Incoming/_cbz/C/Chainsaw Man v07 (2021) (Digital) (danke-Empire).cbz :: Chainsaw Man - c053 (v07) - p000 [Cover] [dig] [In a Dream] [VIZ Media] [danke-Empire].jpg
2022-06-06T12:27:10 | comicapi.comicarchive | ERROR | Error reading zip archive [[Errno 22] Invalid argument]: /media/Collections/Comics/Incoming/_cbz/C/Chainsaw Man v07 (2021) (Digital) (danke-Empire).cbz :: Chainsaw Man - c053 (v07) - p000 [Cover] [dig] [In a Dream] [VIZ Media] [danke-Empire].jpg
2022-06-06T12:27:10 | comicapi.comicarchive | ERROR | Error reading in page 0. Substituting logo page.
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 850, in get_page
    image_data = self.archiver.read_file(filename) or bytes()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 217, in read_file
    data = zf.read(archive_file)
  File "/usr/lib/python3.10/zipfile.py", line 1473, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.10/zipfile.py", line 1528, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib/python3.10/zipfile.py", line 744, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
2022-06-06T12:27:10 | comicapi.comicarchive | ERROR | Error reading in page 0. Substituting logo page.
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 850, in get_page
    image_data = self.archiver.read_file(filename) or bytes()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 217, in read_file
    data = zf.read(archive_file)
  File "/usr/lib/python3.10/zipfile.py", line 1473, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.10/zipfile.py", line 1528, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib/python3.10/zipfile.py", line 744, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
2022-06-06T12:27:18 | comicapi.comicarchive | ERROR | Error reading zip archive [[Errno 22] Invalid argument]: /media/Collections/Comics/Incoming/_cbz/C/Chainsaw Man v07 (2021) (Digital) (danke-Empire).cbz :: Chainsaw Man - c053 (v07) - p000 [Cover] [dig] [In a Dream] [VIZ Media] [danke-Empire].jpg
2022-06-06T12:27:18 | comicapi.comicarchive | ERROR | Error reading in page 0. Substituting logo page.
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 850, in get_page
    image_data = self.archiver.read_file(filename) or bytes()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 217, in read_file
    data = zf.read(archive_file)
  File "/usr/lib/python3.10/zipfile.py", line 1473, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.10/zipfile.py", line 1528, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib/python3.10/zipfile.py", line 744, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
2022-06-06T12:27:18 | comicapi.comicarchive | ERROR | Error reading zip archive [Bad magic number for file header]: /media/Collections/Comics/Incoming/_cbz/C/Chainsaw Man v07 (2021) (Digital) (danke-Empire).cbz :: Chainsaw Man - c053 (v07) - p001 [dig] [In a Dream] [VIZ Media] [danke-Empire].png
2022-06-06T12:27:18 | comictagger | CRITICAL | Uncaught exception: BadZipFile: Bad magic number for file header
Traceback (most recent call last):
  File "/home/scuttle/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 1086, in commit_metadata
    success = self.comic_archive.write_metadata(self.metadata, self.save_data_style)
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 817, in write_metadata
    retcode = self.write_cix(metadata)
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 1026, in write_cix
    self.apply_archive_info_to_metadata(metadata, calc_page_sizes=True)
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 1161, in apply_archive_info_to_metadata
    data = self.get_page(idx)
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 850, in get_page
    image_data = self.archiver.read_file(filename) or bytes()
  File "/home/scuttle/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 217, in read_file
    data = zf.read(archive_file)
  File "/usr/lib/python3.10/zipfile.py", line 1473, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.10/zipfile.py", line 1533, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

```

**Comment by lordwelch** [comment]
@ScuttleSE if this happens again feel free to re-open

**Comment by edgehub-cloud** [comment]
@lordwelch  thou has happened with me

**Comment by lordwelch** [comment]
@edgehub-cloud please open a new issue and provide logs from when the issue happened
