### ISSUE TITLE
zipfile.py crashes

### ISSUE THREAD

**Issue by edgehub-cloud** [comictagger/comictagger#329]
--------------------------------------------------------------------------
-----> Twin Star Exorcists (2015) #13 Onmyoji (9/2018) -- score: 0
--------------------------------------------------------------------------
2022-07-08T11:01:58 | comicapi.comicarchive | ERROR | Error rebuilding zip
 file: kavitaManga/Twin Star Exorcists/Twin Star Exorcists v13 #13 (2018)
(Digital) (KG Manga).cbz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/comicapi/comicarchive.py",
line 245, in rebuild_zip_file
    zout.writestr(item, buffer)
  File "/usr/lib/python3.8/zipfile.py", line 1817, in writestr
    dest.write(data)
  File "/usr/lib/python3.8/zipfile.py", line 1182, in close
    self._fileobj.seek(self._zipfile.start_dir)
OSError: [Errno 29] Illegal seek
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/zipfile.py", line 1838, in close
    self.fp.seek(self.start_dir)
OSError: [Errno 29] Illegal seek
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/comicapi/comicarchive.py",
line 248, in rebuild_zip_file
    zout.comment = zin.comment
  File "/usr/lib/python3.8/zipfile.py", line 1312, in __exit__
    self.close()
  File "/usr/lib/python3.8/zipfile.py", line 1843, in close
    self._fpclose(fp)
  File "/usr/lib/python3.8/zipfile.py", line 1953, in _fpclose
    fp.close()
OSError: [Errno 29] Illegal seek
2022-07-08T11:02:01 | comicapi.comicarchive | ERROR | writing zip file fai
led [[Errno 1] Operation not permitted]: kavitaManga/Twin Star Exorcists/T
win Star Exorcists v13 #13 (2018) (Digital) (KG Manga).cbz
2022-07-08T11:02:01 | comictaggerlib.cli | ERROR | The tag save seemed to
fail!
Processing kavitaManga/Twin Star Exorcists/Twin Star Exorcists v14 #14 (20
19) (Digital) (1r0n) (f2).cbz...
^C

**Comment by lordwelch** [comment]
From the little I can find on this it appears to be a hardware issue or filesystem issue.
Try attaching an unused flashdrive to your computer, format it, copy over the cbz file and try again

Also if you could simply attach the entire log file when posting an issue it would be appreciated.

**Comment by edgehub-cloud** [comment]
@lordwelch  I am using a dedicated server. It runs on who e system (raid 0 setup)

**Comment by lordwelch** [comment]
There are few computer systems dedicated servers or otherwise that do not have USB ports

**Comment by lordwelch** [comment]
@edgehub-cloud were you able to figure out what happened? This appears to be a hardware/filesystem issue were you able to attempt on an external drive?

**Comment by lordwelch** [comment]
If you can provide full logs and/or more information feel free to re-open
