### ISSUE TITLE
comictagger | ERROR | CLI mode failed

### ISSUE THREAD

**Issue by zachstultz** [comictagger/comictagger#333]
Decided to update comictagger, and now I get this. Running the exact same command that ran perfectly on the old verison.

Version:
Python 3.8.10

Command:
`python3 /data/docker/scripts/comictagger/comictagger.py -p -t cr manga.cbz`

Error:
`2022-07-19T07:19:05 | comictagger | ERROR | CLI mode failed
Traceback (most recent call last):
  File "/data/docker/scripts/comictagger/comictaggerlib/main.py", line 173, in ctmain
    cli.cli_mode(opts, settings)
  File "/data/docker/scripts/comictagger/comictaggerlib/cli.py", line 175, in cli_mode
    process_file_cli(f, opts, settings, match_results)
  File "/data/docker/scripts/comictagger/comictaggerlib/cli.py", line 223, in process_file_cli
    if not ca.seems_to_be_a_comic_archive():
  File "/data/docker/scripts/comictagger/comicapi/comicarchive.py", line 810, in seems_to_be_a_comic_archive
    self.get_number_of_pages() > 0
  File "/data/docker/scripts/comictagger/comicapi/comicarchive.py", line 952, in get_number_of_pages
    self.page_count = len(self.get_page_name_list())
  File "/data/docker/scripts/comictagger/comicapi/comicarchive.py", line 937, in get_page_name_list
    files = cast(list[str], natsort.natsorted(files, alg=natsort.ns.IC | natsort.ns.I | natsort.ns.U))
TypeError: 'type' object is not subscriptable`

**Comment by lordwelch** [comment]
Currently ComicTagger only supports python3.9
