### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#35]
_From [olin...@gmail.com](https://code.google.com/u/117177305437248657771/) on December 06, 2013 18:25:47_

What steps will reproduce the problem? 1. comictagger.py -v -e --delete-rar Earth\ X\ 012.cbr What is the expected output? What do you see instead? comictagger.py -v -e --delete-rar Earth\ X\ 012.cbr
Traceback (most recent call last):
  File "/usr/local/bin/comictagger.py", line 5, in <module>
    ctmain()
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/main.py", line 54, in ctmain
    cli.cli_mode( opts, settings )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 184, in cli_mode
    process_file_cli( f, opts, settings, match_results )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 218, in process_file_cli
    if not ca.seemsToBeAComicArchive():
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 612, in seemsToBeAComicArchive
    ( self.getNumberOfPages() > 2)
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 769, in getNumberOfPages
    self.page_count = len( self.getPageNameList( ) )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 745, in getPageNameList
    files = self.archiver.getArchiveFilenameList()
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 113, in getArchiveFilenameList
    zf = zipfile.ZipFile( self.path, 'r' )
  File "/usr/lib/python2.7/zipfile.py", line 766, in **init**
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 825, in _RealGetContents
    fp.seek(self.start_dir, 0)
IOError: [Errno 22] Invalid argument What version of the product are you using? On what operating system? 1.1.9, Ubuntu 12.10 Please provide any additional information below. The file extracts fine from the CL. Contents:
EarthX12p00.jpg
EarthX12p01.jpg
EarthX12p02and03.jpg
EarthX12p04and05.jpg
EarthX12p06and07.jpg
EarthX12p08.jpg
EarthX12p09.jpg
EarthX12p10and11.jpg
EarthX12p12.jpg
EarthX12p13.jpg
EarthX12p14.jpg
EarthX12p15.jpg
EarthX12p16.jpg
EarthX12p17.jpg
EarthX12p18and19.jpg
EarthX12p20.jpg
EarthX12p21.jpg
EarthX12p22and23.jpg
EarthX12p24.jpg
EarthX12p25.jpg
EarthX12p26.jpg
EarthX12p27.jpg
EarthX12p28.jpg
EarthX12p29.jpg
EarthX12p30.jpg
EarthX12p31.jpg
EarthX12p32.jpg

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=35_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 22, 2014 13:43:44_

Do you still have the offending file? 

In the meantime, I've added exception handling to at least not crash when this happens.

**Status:** Accepted

**Comment by lordwelch** [comment]
Closing due to age.
