### ISSUE TITLE
AttributeError: 'PathDistribution' object has no attribute 'name'

### ISSUE THREAD

**Issue by jacobkossman** [comictagger/comictagger#375]
installed using `pip3.9 install 'comictagger[CBR]`

version is `1.5.0`

trying to run any command besides -h or --version results in the following:

```
2022-09-19T22:19:50 | comictagger | CRITICAL | Uncaught exception: AttributeError: 'PathDistribution' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/XXXX/.local/bin/comictagger", line 8, in <module>
    sys.exit(ctmain())
  File "/home/XXXX/.local/lib/python3.9/site-packages/comictaggerlib/main.py", line 161, in ctmain
    for pkg in sorted(importlib_metadata.distributions(), key=lambda x: x.name):
  File "/home/XXXX/.local/lib/python3.9/site-packages/comictaggerlib/main.py", line 161, in <lambda>
    for pkg in sorted(importlib_metadata.distributions(), key=lambda x: x.name):
AttributeError: 'PathDistribution' object has no attribute 'name'
```

**Comment by lordwelch** [comment]
Thanks for the issue!
I did not specify any version constraints for the importlib_metadata package and it appears that you have an old version of importlib_metadata you can install a compatible version by running `pip3.9 install importlib_metadata>=3.3.0`
The next version will have a proper minimum version set

**Comment by jacobkossman** [comment]
Voila. Thanks for quick help!

For those with this issue potentially in the future (hi from the past) use quotes:

`pip3.9 install 'importlib_metadata>=3.3.0'`
