### ISSUE TITLE
Crash when trying to rename

### ISSUE THREAD

**Issue by potter-jason** [comictagger/comictagger#446]
I'm on 1.55, fresh install

AttributeError: 'Namespace' object has no attribute 'filename_rename_set_extension_based_on_archive'
user@localhost:~/Projects/comictagger> python3 comictagger.py
2023-03-30T06:28:36 | comictagger | CRITICAL | Uncaught exception: AttributeError: 'Namespace' object has no attribute 'filename_rename_set_extension_based_on_archive'
Traceback (most recent call last):
  File "/home/user/Projects/comictagger/comictaggerlib/taggerwindow.py", line 2050, in rename_archive
    dlg = RenameWindow(self, ca_list, self.load_data_style, self.config, self.talkers)
  File "/home/user/Projects/comictagger/comictaggerlib/renamewindow.py", line 67, in __init__
    self.do_preview()
  File "/home/user/Projects/comictagger/comictaggerlib/renamewindow.py", line 98, in do_preview
    new_ext = self.config_renamer(ca)
  File "/home/user/Projects/comictagger/comictaggerlib/renamewindow.py", line 76, in config_renamer
    if self.config[0].filename_rename_set_extension_based_on_archive:
AttributeError: 'Namespace' object has no attribute 'filename_rename_set_extension_based_on_archive'

**Comment by lordwelch** [comment]
You are not on 1.5.5 you are using the latest code committed to the repository which is [207 commits](https://github.com/comictagger/comictagger/compare/1.5.5...develop) ahead of 1.5.5.
Please see the [PIP Installation](https://github.com/comictagger/comictagger#pip-installation) section for installing ComicTagger on Linux.
