### ISSUE TITLE
Series window expects year as int not None

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#523]
GenericMetadata defaults year to `None` but the series window expects an `int` and so crashes:
```
Traceback (most recent call last):
  File "comictagger/comictaggerlib/seriesselectionwindow.py", line 546, in cell_double_clicked
    self.show_issues()
  File "comictagger/comictaggerlib/seriesselectionwindow.py", line 337, in show_issues
    title = f"{series.name} ({series.start_year:04}) - "
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by lordwelch** [comment]
That's because ComicVine always had a year...
