### ISSUE TITLE
Error writing tags to CBR on MacOS

### ISSUE THREAD

**Issue by jpleite** [comictagger/comictagger#535]
Hi. First of all great work

I tried both versions 1.6.0-alpha.6: Hal Jordan and 1.5.5 on a Mac M1. They both work and save info on cbz files. However I'm not able to save the tags in CBR files. Installed rar using brew install rar and both rar and Unrar work from command line. I get error 9 and I'm not able to understand why. Rar version is RAR 6.23

Bellow a copy of the log

2023-09-19T12:16:55 | comictagger | INFO | ComicTagger Version: 1.6.0a7.dev0 running on: Darwin PyInstaller: Yes
2023-09-19T12:16:55 | comictagger | DEBUG | user_data_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-09-19T12:16:55 | comictagger | DEBUG | user_config_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-09-19T12:16:55 | comictagger | DEBUG | user_cache_dir: /Users/jpleite/Library/Caches/ComicTagger
2023-09-19T12:16:55 | comictagger | DEBUG | user_state_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-09-19T12:16:55 | comictagger | DEBUG | user_log_dir: /Users/jpleite/Library/Logs/ComicTagger
2023-09-19T12:16:55 | comictagger | DEBUG | Installed Packages
2023-09-19T12:16:55 | comictagger | DEBUG | comictagger	1.6.0a7.dev0
2023-09-19T12:16:55 | comictagger | DEBUG | importlib-metadata	6.8.0
2023-09-19T12:16:55 | comictagger | DEBUG | metron-talker	0.1.1
2023-09-19T12:16:55 | comictagger | DEBUG | pycountry	22.3.5
2023-09-19T12:16:55 | comictagger | DEBUG | wheel	0.41.2
2023-09-19T12:17:13 | comicapi.archivers.rar | ERROR | Error writing rar archive [exitcode: 9]: /Users/jpleite/Downloads/Ast3r1x - PT0001 - 2020.cbr :: ComicInfo.xml

**Comment by lordwelch** [comment]
This sounds like macOS is getting in the way that error code should mean that it isn't allowed to create a file in that directory.
In System Settings -> Privacy and Security -> files and folders you should see an entry that looks like this
<img width="459" alt="Screenshot 2023-09-19 at 11 06 31 AM" src="https://github.com/comictagger/comictagger/assets/7547075/83fbf3fb-f818-4170-b7c7-88032dfaf94f">

**Comment by jpleite** [comment]
thanks @lordwelch  it was already enabled. I even tried before with full disk access. Still the same error. Forgot to mention I'm using latest beta version of Sonoma. Any log I can send that might be useful? Thanks in advance

**Comment by lordwelch** [comment]
That's actually what I just tested on except it's an M2 air

**Comment by lordwelch** [comment]
Try running this in the terminal
```zsh
xattr -d com.apple.quarantine "$(dirname $(readlink -f $(which rar)))/"*
```

This will remove the quarantine flag that downloaded items get from the rar program
and then can you try downloading the cbr file from here https://archive.org/download/CoryDoctorowsFuturisticTalesOfTheHereAndNow
and move it out of your downloads folder before trying to save to it

**Comment by jpleite** [comment]
That is strange. It does not seem a file permission issue as I can write tags in cbz files. Any other suggestions?

**Comment by jpleite** [comment]
> Try running this in the terminal
> 
> ```shell
> xattr -d com.apple.quarantine "$(dirname $(readlink -f $(which rar)))/"*
> ```
> 
> This will remove the quarantine flag that downloaded items get from the rar program and then can you try downloading the cbr file from here https://archive.org/download/CoryDoctorowsFuturisticTalesOfTheHereAndNow and move it out of your downloads folder before trying to save to it

Thanks. Tried exactly as you described. Still the same error. RAR has quarantine removed and it's bin is under rar -> /opt/homebrew/Caskroom/rar/6.23/rar/rar installed via homebrew

**Comment by lordwelch** [comment]
lets try using rar manually
```zsh
echo testing rar edit | rar c  '~/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr'
rar cw '~/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr'
```

**Comment by jpleite** [comment]
Thanks @lordwelch .

just had to correct your command to (remove the '):

`echo testing rar edit | rar c ~/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr
rar cw ~/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr`

and the output is as expected
<img width="1034" alt="Screenshot 2023-09-21 at 14 20 17" src="https://github.com/comictagger/comictagger/assets/8203292/5c66d4c2-2715-4f77-b323-4284e4568622">

**Comment by jpleite** [comment]
@lordwelch any more hints? actually the command you sent works with apostrophes on path but only full path like
`echo testing rar edit | rar c '/Users/jpleite/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr'
rar cw '/Users/jpleite/Downloads/Cory_Doctorows_Futuristic_Tales_of_the_Here_and_Now_CBR.cbr'`

**Comment by lordwelch** [comment]
Turns out I don't log the output of the rar command, I'll have another alpha put up this weekend that logs it and we can hopefully see what's failing.

**Comment by jpleite** [comment]
thanks @lordwelch I'll try again after that release

**Comment by jpleite** [comment]
Hi @lordwelch did you manage to compile that build? Thanks in advance

**Comment by lordwelch** [comment]
It will be published in a few minutes

**Comment by jpleite** [comment]
Hi @lordwelch . Just tried and have the following error at startup: Failed to load any talkers, please re-install and check the log located in '/Users/jpleite/Library/Logs/ComicTagger' for more details. The log states:

> 2023-10-07T08:14:06 | comictagger | INFO | ComicTagger Version: 1.6.0a7 running on: Darwin PyInstaller: Yes
2023-10-07T08:14:06 | comictagger | DEBUG | user_data_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-10-07T08:14:06 | comictagger | DEBUG | user_config_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-10-07T08:14:06 | comictagger | DEBUG | user_cache_dir: /Users/jpleite/Library/Caches/ComicTagger
2023-10-07T08:14:06 | comictagger | DEBUG | user_state_dir: /Users/jpleite/Library/Application Support/ComicTagger
2023-10-07T08:14:06 | comictagger | DEBUG | user_log_dir: /Users/jpleite/Library/Logs/ComicTagger
2023-10-07T08:14:06 | comicapi.comicarchive | WARNING | Failed to load talker: rar
2023-10-07T08:14:06 | comicapi.comicarchive | WARNING | Failed to load talker: sevenzip
2023-10-07T08:14:06 | comictalker | ERROR | Failed to load talker: metron
Traceback (most recent call last):
  File "comictalker/__init__.py", line 28, in get_talkers
  File "setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'metron_talker'
2023-10-07T08:14:06 | comictalker | ERROR | Failed to load talker: comicvine
Traceback (most recent call last):
  File "comictalker/__init__.py", line 28, in get_talkers
  File "setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'comictalker.talkers'
2023-10-07T08:14:06 | comictagger | DEBUG | Installed Packages
2023-10-07T08:14:06 | comictagger | DEBUG | comictagger	1.6.0a7
2023-10-07T08:14:06 | comictagger | DEBUG | importlib-metadata	6.8.0
2023-10-07T08:14:06 | comictagger | DEBUG | metron-talker	0.1.1
2023-10-07T08:14:06 | comictagger | DEBUG | pycountry	22.3.5
2023-10-07T08:14:06 | comictagger | DEBUG | wheel	0.41.2

**Comment by lordwelch** [comment]
[1.6.0-alpha.8] has the startup issue fixed

[1.6.0-alpha.8]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.8

**Comment by jpleite** [comment]
Thanks @lordwelch. Already tried. The log states

> 2023-10-09T12:02:52 | comicapi.archivers.rar | ERROR | Error writing rar archive [exitcode: 9]: /Users/jpleite/Downloads/Asterix - PT0001 - Astérix, o Gaulês (1961).cbr :: ComicInfo.xml :: b'\nCannot create __rar_99329.35340\nRead-only file system'

**Comment by lordwelch** [comment]
Can you try out PR #554 and let me know if it works?
https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests

**Comment by jpleite** [comment]
Just tried Just tried app from #554 . Still get the following error

> 2023-10-10T12:47:12 | comicapi.comicarchive | ERROR | comicapi/archivers/rar.py:172: Error saving CIX! for /Users/jpleite/Downloads/Asterix - PT0001 - Astérix, o Gaulês (1961).cbr: [Errno 20] Not a directory: PosixPath('/Users/jpleite/Downloads/Asterix - PT0001 - Astérix, o Gaulês (1961).cbr')

**Comment by lordwelch** [comment]
I've updated #554 can you try again?

**Comment by jpleite** [comment]
Hi @lordwelch . I'm happy to report it did work this time. Thank you for your time and patience. I'm just curious about what was the matter?

**Comment by lordwelch** [comment]
the rar command creates a temporary file when it modifies the the cbr comic and it was trying to create it in it's *current directory* which was probably a temporary directory and for some reason you didn't have access to it, so I've set the working directory to be the same as the file that gets modified.
