### ISSUE TITLE
Alpha 7 not opening

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#551]
2023-10-07T14:00:05 | comicapi.comicarchive | WARNING | Failed to load talker: rar
2023-10-07T14:00:05 | comicapi.comicarchive | WARNING | Failed to load talker: sevenzip
2023-10-07T14:00:05 | comictalker | ERROR | Failed to load talker: comicvine
Traceback (most recent call last):
  File "comictalker\__init__.py", line 28, in get_talkers
  File "importlib_metadata\__init__.py", line 209, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'comictalker.talkers'
2023-10-07T14:00:05 | comictalker | ERROR | Failed to load talker: metron
Traceback (most recent call last):
  File "comictalker\__init__.py", line 28, in get_talkers
  File "importlib_metadata\__init__.py", line 209, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'metron_talker'

-->
Tested on 2 different systems (Windows 10 and 11)

**Comment by lordwelch** [comment]
Fixed in [1.6.0-alpha.8]

[1.6.0-alpha.8]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.8
