### ISSUE TITLE
Cannot Open CBZ files on Linux after #550

### ISSUE THREAD

**Issue by ConstrictM** [comictagger/comictagger#558]
I think this might be a simple fix to Line 28 to remove True in the chardet.detect call in comicapi/archivers/zip.py

encoding = chardet.detect(zf.comment)

```
2023-10-22T16:27:11 | comictagger | CRITICAL | Uncaught exception: TypeError: detect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comictaggerlib/taggerwindow.py", line 998, in select_file
    self.fileSelectionList.add_path_list(file_list)
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comictaggerlib/fileselectionlist.py", line 205, in add_path_list
    row = self.add_path_item(f)
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comictaggerlib/fileselectionlist.py", line 316, in add_path_item
    self.update_row(row)
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comictaggerlib/fileselectionlist.py", line 351, in update_row
    if fi.ca.has_cbi():
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comicapi/comicarchive.py", line 315, in has_cbi
    comment = self.archiver.get_comment()
  File "/mnt/home/constrict/.local/lib/python3.10/site-packages/comicapi/archivers/zip.py", line 28, in get_comment
    encoding = chardet.detect(zf.comment, True)
TypeError: detect() takes 1 positional argument but 2 were given
```

**Comment by lordwelch** [comment]
update chardet `pip install -U chardet`
