### ISSUE TITLE
Save settings with Path - not serializable

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#567]
JSON Encoder(/Decoder?) required.

```
TypeError: Object of type PosixPath is not JSON serializable
2023-11-14T22:53:17 | settngs | ERROR | Failed to save config file: .config/ComicTagger/settings.json
Traceback (most recent call last):
  File "/workspace/comictagger/venv/lib/python3.10/site-packages/settngs/__init__.py", line 533, in save_file
    json_str = json.dumps(file_options, indent=2)
  File "/usr/lib64/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**Comment by mizaki** [comment]
I'm not sure on the value of
```
# Parse string values into their real types
        typ = definitions.v[dest].type
        if isinstance(widget_value, str) and typ:
            widget_value = typ(widget_value)
```
When to be saved (taking Path as an example), it's going to mean taking the string?

**Comment by lordwelch** [comment]
`typ` is the type argument from argparse it is a callable object that takes a single string argument and returns a value.
So here we check if the value we have, `widget_value`, is a string if it is and we have a type callable object that is truthy/is not None, we then use the type callable object to transform the value into whatever it should be. In the case of a setting definition like this
```python
        parser.add_setting(
            f"--gcd-path",
            display_name="SQLite DB path",
            help="The path of the GCD SQLite file",
            type=pathlib.Path,
        )
```
you end up with this equivalent code
```python
        # Parse string values into their real types
        typ = pathlib.Path  # definitions.v[dest].type
        if isinstance(widget_value, str) and typ:
            widget_value = typ(widget_value)
```
