### ISSUE TITLE
1.6.0-alpha.12 - Startup Failed: TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by DieselTech** [comictagger/comictagger#609]
Trying the latest pre-release on Win 10 x64. Application fails to startup:

2024-02-23T12:53:01 | comictagger | ERROR | GUI mode failed
Traceback (most recent call last):
  File "comictaggerlib\gui.py", line 136, in open_tagger_window
  File "comictaggerlib\taggerwindow.py", line 221, in __init__
TypeError: 'int' object is not iterable

**Comment by lordwelch** [comment]
Delete your settings file. Or you can just delete the line with `save_data_style`

**Comment by DieselTech** [comment]
Deleting the `save_data_style = "1",` line worked.
