### ISSUE TITLE
Latest commit (5010ca6) crash on tag write GUI/CLI both

### ISSUE THREAD

**Issue by Cducharme84** [comictagger/comictagger#647]
I've used both the GUI and CLI and a combo of both overlay modes for modify overlay within the GUI settings and using the CLI arguments with the merge lists argument both off and on in GUI/CLI modes. At all points when going to save the tags this stack-dump happens.
```
Traceback (most recent call last):
  File "/home/christian/.local/lib/python3.12/site-packages/comictaggerlib/main.py", line 317, in main
    raise SystemExit(cli.CLI(self.config[0], self.talkers).run())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comictaggerlib/cli.py", line 105, in run
    res, match_results = self.process_file_cli(self.config.Commands__command, f, match_results)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comictaggerlib/cli.py", line 706, in process_file_cli
    return self.save(ca, match_results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comictaggerlib/cli.py", line 554, in save
    if self.actual_metadata_save(ca, res.md):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comictaggerlib/cli.py", line 139, in actual_metadata_save
    if not ca.write_metadata(md, style):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comicapi/comicarchive.py", line 229, in write_metadata
    return metadata_styles[style].set_metadata(metadata, self.archiver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comicinfoxml.py", line 121, in set_metadata
    return archive.write_file(self.file, self._bytes_from_metadata(metadata, xml))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comicinfoxml.py", line 146, in _bytes_from_metadata
    root = self._convert_metadata_to_xml(metadata, xml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/.local/lib/python3.12/site-packages/comicinfoxml.py", line 195, in _convert_metadata_to_xml
    if credit['role'].casefold() in GenericMetadata.writer_synonyms:
       ~~~~~~^^^^^^^^
TypeError: 'Credit' object is not subscriptable

```

I'm happy to test around with stuff if needed to help identify the cause as, I'm not sure if you'd noticed by my zeal, I'm quite keen on this feature to fill in my missing genres from the GCD db without ruining the summaries from CV tagging previus.

**Comment by lordwelch** [comment]
You need to update comicinfoxml
`pip install -u comicinfo.xml`

**Comment by Cducharme84** [comment]
You rock! Just for folks who may encounter this once the next alpha goes live `pip install -U comicinfoxml` was what did the trick, took me a moment to remember update is -U not -u.

And now off to the races!
