### ISSUE TITLE
Error on quitting GUI with 1.6.0a21: Uncaught exception: KeyError: 'Quick Tag'

### ISSUE THREAD

**Issue by beville** [comictagger/comictagger#673]
This seems to always happen on quitting the GUI application.

```
$ comictagger --verbose
2024-08-24T10:08:39 | comictagger | INFO | ComicTagger Version: 1.6.0a21 running on: Linux PyInstaller: No
2024-08-24T10:08:46 | comictagger | CRITICAL | Uncaught exception: KeyError: 'Quick Tag'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/comictaggerlib/taggerwindow.py", line 2021, in closeEvent
    ctsettings.save_file(self.config, self.config[0].Runtime_Options__config.user_config_dir / "settings.json")
  File "/usr/local/lib/python3.10/dist-packages/comictaggerlib/ctsettings/__init__.py", line 107, in save_file
    file_options["Quick Tag"]["url"] = str(file_options["Quick Tag"]["url"])
KeyError: 'Quick Tag'
2024-08-24T10:08:50 | comictagger | WARNING | Exception ignored
```

**Comment by lordwelch** [comment]
I knew I broke something

**Comment by lordwelch** [comment]
Fixed in the latest alpha
