### ISSUE TITLE
Uncaught exception: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by declankenny** [comictagger/comictagger#688]
Trying with both 1.6.0b2 and 1.6.0b3

2024-09-26T11:12:12 | comictagger | CRITICAL | Uncaught exception: TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "comictaggerlib\taggerwindow.py", line 1923, in auto_tag
  File "comictaggerlib\taggerwindow.py", line 1728, in identify_and_tag_single_archive
  File "comictaggerlib\issueidentifier.py", line 184, in identify
  File "comictaggerlib\issueidentifier.py", line 567, in _search_for_issues
  File "comictalker\talkers\comicvine.py", line 296, in search_for_series
  File "comictalker\talkers\comicvine.py", line 611, in _get_cv_content
TypeError: 'NoneType' object is not subscriptable

**Comment by lordwelch** [comment]
The CV API is down you can check at https://comicvine.gamespot.com/api, this error has been fixed for the next beta
