### ISSUE TITLE
Error during auto-tagging

### ISSUE THREAD

**Issue by mrsilva** [comictagger/comictagger#713]
When ComicTagger is doing auto-tagging, it will sometimes throw an error (screenshot attached). Even if i choose 'Ignore' it will stop the auto-tagging process, even though it seems to still be working.

Very frustrating when auto-tagging is running for a couple days and I have to restart.

The error appears after this output:
"Cover: 0
Cover: double page
Searching for Excalibur - The Sword Is Drawn #0 ..."

Ask:
- more descriptive error to see why this occurred
- make the error recoverable (either I click on Ignore and it continues, or it continues in the background automatically while showing the error dialog), so the tagging continues

Thanks!

![screenshot](https://github.com/user-attachments/assets/a15bcd7c-5b19-4ec0-875d-18a750a446a0)

**Comment by mrsilva** [comment]
This is what appears in the console. Is it related to the rate exceeded?

![console](https://github.com/user-attachments/assets/73f45957-cbd9-4b47-bc72-11696d1d8121)

**Comment by mizaki** [comment]
Which version of CT is this?

**Comment by mrsilva** [comment]
ComicTagger-1.6.0b3.dev0-win-AMD64.exe.zip  running under Windows 11

**Comment by mizaki** [comment]
Is it always the same with that file? I tried a file named the same and it was fine. A full log might help too.

**Comment by mrsilva** [comment]
The log file has the following, it stops after the crash:

-----------------------------------------------------------------------------------------------------
...
2025-01-01T04:03:27 | comictaggerlib.issueidentifier | INFO | Found 1 series that have an issue #2
2025-01-01T04:03:27 | comictaggerlib.issueidentifier | INFO | Examining covers for Series ID: 9111 Gambit (1999):
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO |  -  000
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | best score 000
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | 
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | Compared to covers in 1 issue(s): [0]
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | -----> Gambit (1999) #2 Stormbringers (3/1999) -- score: 0
2025-01-01T04:03:28 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2025-01-01T04:03:28 | comictalker.talkers.comicvine | DEBUG | Fetching issue by issue ID: 66891
2025-01-01T04:03:28 | comictalker.talkers.comicvine | DEBUG | Issue cached: False
2025-01-01T04:03:30 | comictagger | CRITICAL | Uncaught exception: TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "comictaggerlib\taggerwindow.py", line 1923, in auto_tag
  File "comictaggerlib\taggerwindow.py", line 1804, in identify_and_tag_single_archive
  File "comictalker\talkers\comicvine.py", line 368, in fetch_comic_data
  File "comictalker\talkers\comicvine.py", line 821, in _fetch_issue_data_by_issue_id
  File "comictalker\talkers\comicvine.py", line 611, in _get_cv_content
TypeError: 'NoneType' object is not subscriptable
2025-01-01T09:20:54 | comictagger | WARNING | Exception ignored
-----------------------------------------------------------------------------------------------------

Also found 3 other exceptions:

-----------------------------------------------------------------------------------------------------
...
2024-12-29T21:59:40 | comictaggerlib.issueidentifier | INFO | Compared to covers in 1 issue(s): [5]
2024-12-29T21:59:40 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2024-12-29T21:59:40 | comictaggerlib.issueidentifier | INFO | -----> Shanda the Panda (1993) #11  (9/1995) -- score: 5
2024-12-29T21:59:40 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2024-12-29T21:59:40 | comictalker.talkers.comicvine | DEBUG | Fetching issue by issue ID: 171080
2024-12-29T21:59:40 | comictalker.talkers.comicvine | DEBUG | Issue cached: False
2024-12-29T21:59:40 | comictalker.talkers.comicvine | DEBUG | Fetching series info: 6591
2024-12-29T21:59:40 | comictalker.talkers.comicvine | DEBUG | Series cached: True
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | DEBUG | Width: 1280 Height: 1996, ratio: 0  0 ratio met: False
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | DEBUG | Width: 1280 Height: 1996, ratio: 0  0 ratio met: False
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | DEBUG | Width: 1280 Height: 1996, ratio: 0  0 ratio met: False
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | Using Comic Vine to search for:
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | 	Series: Secret Files - Invasion Day
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | 	Issue:  1
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | 	Year:   1996
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | 	Count:  2
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | Cover: 0
2024-12-29T21:59:47 | comictaggerlib.issueidentifier | INFO | Searching for Secret Files - Invasion Day #1 ...
2024-12-29T21:59:47 | comictalker.talkers.comicvine | INFO | Comic Vine searching: secret files invasion day
2024-12-29T21:59:48 | comictalker.talkers.comicvine | DEBUG | Search for 'Secret Files - Invasion Day' cached: False
2024-12-29T21:59:50 | comictagger | CRITICAL | Uncaught exception: TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "comictaggerlib\taggerwindow.py", line 1923, in auto_tag
  File "comictaggerlib\taggerwindow.py", line 1728, in identify_and_tag_single_archive
  File "comictaggerlib\issueidentifier.py", line 184, in identify
  File "comictaggerlib\issueidentifier.py", line 567, in _search_for_issues
  File "comictalker\talkers\comicvine.py", line 296, in search_for_series
  File "comictalker\talkers\comicvine.py", line 611, in _get_cv_content
TypeError: 'NoneType' object is not subscriptable
...
-----------------------------------------------------------------------------------------------------


-----------------------------------------------------------------------------------------------------
...
2024-12-30T15:05:49 | comictaggerlib.issueidentifier | INFO | Compared to covers in 1 issue(s): [0]
2024-12-30T15:05:49 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2024-12-30T15:05:49 | comictaggerlib.issueidentifier | INFO | -----> Fables (2002) #4 Chapter Four: Remembrance Day (10/2002) -- score: 0
2024-12-30T15:05:49 | comictaggerlib.issueidentifier | INFO | --------------------------------------------------------------------------
2024-12-30T15:05:49 | comictalker.talkers.comicvine | DEBUG | Fetching issue by issue ID: 110322
2024-12-30T15:05:49 | comictalker.talkers.comicvine | DEBUG | Issue cached: False
2024-12-30T15:05:50 | comictalker.talkers.comicvine | DEBUG | Fetching series info: 9723
2024-12-30T15:05:50 | comictalker.talkers.comicvine | DEBUG | Series cached: True
2024-12-30T15:05:55 | comictaggerlib.issueidentifier | DEBUG | Width: 1960 Height: 1500, ratio: 0  0 ratio met: False
2024-12-30T15:05:55 | comictaggerlib.issueidentifier | DEBUG | Width: 1960 Height: 1500, ratio: 0  0 ratio met: False
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | DEBUG | Width: 1960 Height: 1500, ratio: 0  0 ratio met: False
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | Using Comic Vine to search for:
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | 	Series: Excalibur - The Sword Is Drawn
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | 	Issue:  0
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | 	Year:   1988
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | Cover: 0
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | Cover: double page
2024-12-30T15:05:56 | comictaggerlib.issueidentifier | INFO | Searching for Excalibur - The Sword Is Drawn #0 ...
2024-12-30T15:05:56 | comictalker.talkers.comicvine | INFO | Comic Vine searching: excalibur sword drawn
2024-12-30T15:05:57 | comictalker.talkers.comicvine | DEBUG | Search for 'Excalibur - The Sword Is Drawn' cached: False
2024-12-30T15:05:58 | comictagger | CRITICAL | Uncaught exception: TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "comictaggerlib\taggerwindow.py", line 1923, in auto_tag
  File "comictaggerlib\taggerwindow.py", line 1728, in identify_and_tag_single_archive
  File "comictaggerlib\issueidentifier.py", line 184, in identify
  File "comictaggerlib\issueidentifier.py", line 567, in _search_for_issues
  File "comictalker\talkers\comicvine.py", line 296, in search_for_series
  File "comictalker\talkers\comicvine.py", line 611, in _get_cv_content
TypeError: 'NoneType' object is not subscriptable
2024-12-30T15:51:21 | comictagger | WARNING | Exception ignored
...
-----------------------------------------------------------------------------------------------------


-----------------------------------------------------------------------------------------------------
...
2024-12-27T13:52:39 | comictagger | INFO | ComicTagger Version: 1.6.0b3.dev0 running on: Windows PyInstaller: Yes
2024-12-27T13:52:39 | comictagger | DEBUG | user_config_dir: C:\Users\Marisa\AppData\Local\ComicTagger\ComicTagger
2024-12-27T13:52:39 | comictagger | DEBUG | user_cache_dir: C:\Users\Marisa\AppData\Local\ComicTagger\ComicTagger\Cache
2024-12-27T13:52:39 | comictagger | DEBUG | user_log_dir: C:\Users\Marisa\AppData\Local\ComicTagger\ComicTagger\Logs
2024-12-27T13:52:39 | comictagger | DEBUG | user_plugin_dir: C:\Users\Marisa\AppData\Local\ComicTagger\ComicTagger\plugins
2024-12-27T13:52:43 | comictagger | DEBUG | Installed Packages
2024-12-27T13:52:43 | comictagger | DEBUG | altgraph	0.17.4
2024-12-27T13:52:43 | comictagger | DEBUG | autocommand	2.2.2
2024-12-27T13:52:43 | comictagger | DEBUG | backports.tarfile	1.2.0
2024-12-27T13:52:43 | comictagger | DEBUG | comicinfoxml	0.4.0
2024-12-27T13:52:43 | comictagger | DEBUG | comictagger	1.6.0b3.dev0
2024-12-27T13:52:43 | comictagger | DEBUG | importlib_metadata	8.5.0
2024-12-27T13:52:43 | comictagger | DEBUG | importlib_metadata	8.0.0
2024-12-27T13:52:43 | comictagger | DEBUG | importlib_resources	6.4.0
2024-12-27T13:52:43 | comictagger | DEBUG | inflect	7.3.1
2024-12-27T13:52:43 | comictagger | DEBUG | jaraco.collections	5.1.0
2024-12-27T13:52:43 | comictagger | DEBUG | jaraco.context	5.3.0
2024-12-27T13:52:43 | comictagger | DEBUG | jaraco.functools	4.0.1
2024-12-27T13:52:43 | comictagger | DEBUG | jaraco.text	3.12.1
2024-12-27T13:52:43 | comictagger | DEBUG | more-itertools	10.3.0
2024-12-27T13:52:43 | comictagger | DEBUG | packaging	24.1
2024-12-27T13:52:43 | comictagger | DEBUG | platformdirs	4.2.2
2024-12-27T13:52:43 | comictagger | DEBUG | pyinstaller	6.10.0
2024-12-27T13:52:43 | comictagger | DEBUG | tomli	2.0.1
2024-12-27T13:52:43 | comictagger | DEBUG | typeguard	4.3.0
2024-12-27T13:52:43 | comictagger | DEBUG | typeguard	4.3.0
2024-12-27T13:52:43 | comictagger | DEBUG | typing_extensions	4.12.2
2024-12-27T13:52:43 | comictagger | DEBUG | wheel	0.44.0
2024-12-27T13:52:43 | comictagger | DEBUG | wheel	0.43.0
2024-12-27T13:52:43 | comictagger | DEBUG | zipp	3.19.2
2024-12-27T16:22:57 | comictagger | CRITICAL | Uncaught exception: AttributeError: module 'rarfile' has no attribute 'RarFileError'
Traceback (most recent call last):
  File "comicapi\archivers\rar.py", line 318, in get_rar_obj
  File "rarfile.py", line 711, in __init__
  File "rarfile.py", line 932, in _parse
  File "rarfile.py", line 1110, in parse
  File "rarfile.py", line 1136, in _parse_real
  File "rarfile.py", line 1241, in _parse_header
  File "rarfile.py", line 1443, in _parse_block_header
  File "rarfile.py", line 2698, in read
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "comictaggerlib\taggerwindow.py", line 981, in select_folder
  File "comictaggerlib\taggerwindow.py", line 994, in select_file
  File "comictaggerlib\fileselectionlist.py", line 197, in add_path_list
  File "comictaggerlib\fileselectionlist.py", line 272, in add_path_item
  File "comicapi\comicarchive.py", line 202, in seems_to_be_a_comic_archive
  File "comicapi\comicarchive.py", line 332, in get_number_of_pages
  File "comicapi\comicarchive.py", line 326, in get_page_name_list
  File "comicapi\archivers\rar.py", line 211, in get_filename_list
  File "comicapi\archivers\rar.py", line 319, in get_rar_obj
AttributeError: module 'rarfile' has no attribute 'RarFileError'
2024-12-27T16:23:09 | comictagger | WARNING | Exception ignored

-----------------------------------------------------------------------------------------------------

**Comment by mizaki** [comment]
The `RarFileError` is separate issue (I presume). What I'm getting at is is this random or does it happen with specific file/series names every time?

**Comment by mrsilva** [comment]
As far as I can tell its random. Is there a more detailed debug log I can enable?

Yes, the RAR issue seems separate, I just included all the exceptions I could find.

**Comment by mizaki** [comment]
@lordwelch It looks like `if cv_response["status_code"] != 1:` the `cv_response` is `None` but I don't really see how as I would presume a JSONParseError rather than a returned `None`.

I guess this would suppress the error but doesn't fix the problem:
```python
if cv_response.get("status_code") != 1:
```

**Comment by lordwelch** [comment]
I believe this particular error is fixed by the commit directly after the last beta release
